### PR TITLE
Update README with installation instructions

### PR DESCRIPTION
**Pull request by freeslugs**

### CODE REVIEW

**Comment by prakhar1989** [comment]
Nice Gilad! Thanks for the PR! 👍

**Comment by prakhar1989** [comment]
We'll make the README more informative - it looks quite bare at the moment since we hurriedly open-sourced the repo last night.

**Comment by freeslugs** [comment]
@prakhar1989 Of course! Nice work so far. I'll share my ideas tomorrow morning.

**Comment by prakhar1989** [comment]
Great! Looking forward to hearing them :)

**Pull request merged**
